- name: copy custom configurations files for {{current_group}} if exist
  copy:
    src: "{{item}}"
    dest: "{{docker_traefik_dir}}/{{traefik_sub_part[1]}}/{{item|basename}}"
    mode: 0775
  loop: "{{lookup('fileglob','configurations/{{current_group}}/*',wantlist=True,errors='ignore')}}"