- name: copy docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: "{{docker_traefik_dir}}/docker-compose.yml"
    # owner: "{{docker_user}}"
    # group: "{{docker_group}}"
    mode: 0775

- name: copy simple configurations files
  copy:
    src: "{{item}}"
    dest: "{{docker_traefik_dir}}/{{traefik_sub_part[1]}}/{{item|basename}}"
    # owner: "{{docker_user}}"
    # group: "{{docker_group}}"
    mode: 0775
  loop: "{{lookup('fileglob','configurations/*',wantlist=True)}}"

- name: copy template configurations files
  template:
    src: "{{item}}.yml.j2"
    dest: "{{docker_traefik_dir}}/{{traefik_sub_part[1]}}/{{item}}.yml"
    # owner: "{{docker_user}}"
    # group: "{{docker_group}}"
    mode: 0775
  loop: [middlewares,tls]

- name: create cloudflaire API email
  copy:
    dest: "{{docker_traefik_dir}}/{{traefik_sub_part[2]}}/cf_api_email.secret"
    # owner: "{{docker_user}}"
    # group: "{{docker_gorup}}"
    mode: 0660
    content: "{{traefik_cloudflare_api_email}}"
  when: traefik_cloudflare

- name: create cloudflaire API token
  copy:
    dest: "{{docker_traefik_dir}}/{{traefik_sub_part[2]}}/cf_dns_api_token.secret"
    # owner: "{{docker_user}}"
    # group: "{{docker_gorup}}"
    mode: 0660
    content: "{{traefik_cloudflare_api_token}}"
  when: traefik_cloudflare