- name: create traefik dir
  file:
    name: "{{ traefik_dir }}"
    state: directory
    group: "{{ traefik_docker_group }}"
    mode: '02775'

- name: create dirs {{ traefik_sub_part }}
  file:
    name: "{{ traefik_dir }}/{{ item }}"
    state: directory
    group: "{{ traefik_docker_group }}"
    mode: '0775'
  loop: "{{ traefik_sub_part }}"
  when: traefik_sub_part is defined

- name: dockerpull image {{ traefik_image }}
  community.docker.docker_image:
    name: "{{ traefik_image }}"
    source: pull
