---
# tasks file for docker_traefik
- import_tasks: install-traefik.yml
  tags: [install]
- import_tasks: configure-traefik.yml
  tags: [configure]
  notify: docker up traefik
- import_tasks: configure-mgt.yml
  tags: [configure]
 # notify: docker up traefik


