---
- name: docker up traefik
  community.docker.docker_compose_v2:
    project_src: "{{ docker_traefik_dir }}"
    state: present

- name: docker-compose pull traefik
  community.docker.docker_compose_v2:
    project_src: "{{ docker_traefik_dir }}"
    pull: true
